export const categories = [
  'All',
  'Writing',
  'Image',
  'Video',
  'Audio',
  'Marketing',
  'Coding',
  'Productivity',
  'Education',
]

export const tools = [
  { name: 'ChatGPT', description: 'Conversational assistant for brainstorming, writing, analysis, and everyday problem solving.', category: 'Writing', pricing: 'Freemium', url: 'https://chatgpt.com' },
  { name: 'Claude', description: 'AI assistant focused on long-form reasoning, drafting, summarization, and research workflows.', category: 'Writing', pricing: 'Freemium', url: 'https://claude.ai' },
  { name: 'Grammarly', description: 'AI writing companion for grammar, tone, clarity, and polished professional communication.', category: 'Writing', pricing: 'Freemium', url: 'https://www.grammarly.com' },
  { name: 'Perplexity', description: 'Answer engine that combines web search with cited AI summaries for fast research.', category: 'Education', pricing: 'Freemium', url: 'https://www.perplexity.ai' },
  { name: 'Canva AI', description: 'Design platform with AI-powered writing, image generation, layouts, and brand assets.', category: 'Image', pricing: 'Freemium', url: 'https://www.canva.com' },
  { name: 'Adobe Firefly', description: 'Creative generative AI for images, text effects, recoloring, and design experimentation.', category: 'Image', pricing: 'Freemium', url: 'https://firefly.adobe.com' },
  { name: 'Leonardo AI', description: 'AI image generation suite for concept art, product visuals, game assets, and creative teams.', category: 'Image', pricing: 'Freemium', url: 'https://leonardo.ai' },
  { name: 'Runway', description: 'AI creative studio for video generation, editing, background removal, and motion tools.', category: 'Video', pricing: 'Freemium', url: 'https://runwayml.com' },
  { name: 'Descript', description: 'Edit video and podcasts from text with transcription, overdub, captions, and publishing tools.', category: 'Video', pricing: 'Freemium', url: 'https://www.descript.com' },
  { name: 'Synthesia', description: 'Create avatar-led training, support, and marketing videos without a filming setup.', category: 'Video', pricing: 'Paid', url: 'https://www.synthesia.io' },
  { name: 'ElevenLabs', description: 'AI voice generation and dubbing platform for realistic narration and audio localization.', category: 'Audio', pricing: 'Freemium', url: 'https://elevenlabs.io' },
  { name: 'Suno', description: 'Music generation tool for creating songs, demos, and sound ideas from simple prompts.', category: 'Audio', pricing: 'Freemium', url: 'https://suno.com' },
  { name: 'Krisp', description: 'AI noise cancellation and meeting assistant for clearer calls and productivity.', category: 'Audio', pricing: 'Freemium', url: 'https://krisp.ai' },
  { name: 'Jasper', description: 'AI marketing platform for campaigns, brand voice, content briefs, and multi-channel copy.', category: 'Marketing', pricing: 'Paid', url: 'https://www.jasper.ai' },
  { name: 'Copy.ai', description: 'Go-to-market AI platform for sales copy, campaign ideas, repurposing, and workflows.', category: 'Marketing', pricing: 'Freemium', url: 'https://www.copy.ai' },
  { name: 'HubSpot AI', description: 'AI features for CRM, marketing content, sales enablement, and customer support teams.', category: 'Marketing', pricing: 'Freemium', url: 'https://www.hubspot.com/artificial-intelligence' },
  { name: 'GitHub Copilot', description: 'AI pair programmer that suggests code, explains snippets, and supports developer workflows.', category: 'Coding', pricing: 'Paid', url: 'https://github.com/features/copilot' },
  { name: 'Cursor', description: 'AI-first code editor for refactoring, codebase questions, and full-stack implementation.', category: 'Coding', pricing: 'Freemium', url: 'https://www.cursor.com' },
  { name: 'Replit AI', description: 'Cloud coding workspace with AI assistance for building, debugging, and deploying apps.', category: 'Coding', pricing: 'Freemium', url: 'https://replit.com/ai' },
  { name: 'Notion AI', description: 'Workspace AI for drafting documents, summarizing notes, and organizing team knowledge.', category: 'Productivity', pricing: 'Paid', url: 'https://www.notion.so/product/ai' },
  { name: 'Otter.ai', description: 'Meeting transcription, summaries, action items, and searchable conversation intelligence.', category: 'Productivity', pricing: 'Freemium', url: 'https://otter.ai' },
  { name: 'Gamma', description: 'Generate polished presentations, docs, and microsites from prompts or outlines.', category: 'Productivity', pricing: 'Freemium', url: 'https://gamma.app' },
  { name: 'Khanmigo', description: 'AI tutoring and teaching assistant for guided learning, explanations, and classroom support.', category: 'Education', pricing: 'Paid', url: 'https://www.khanmigo.ai' },
  { name: 'Quizlet', description: 'Study platform with AI-powered flashcards, practice tests, tutoring, and learning activities.', category: 'Education', pricing: 'Freemium', url: 'https://quizlet.com' },
]
